---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["python3"]
    state: latest
    update_cache: yes

- name: "download"
  become: true
  command: curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
  args:
    chdir: /root

- name: "upgrade"
  become: true
  command: apt-get install -y nodejs
  args:
    chdir: /root

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present