---
- name: Copy backend files
  become: yes
  copy:
    src:  ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Extract backend files
  become: yes
  shell: |
    cd /home/ubuntu
    tar -vxf artifact.tar.gz
    rm artifact.tar.gz

- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu
    npm install
    pm2 stop default
    pm2 start npm -- start
